name: 'Collect shell versions'
description: 'Collect shell versions'
inputs:
  include-latest:
    description: 'Include "latest" tag in the list of shell versions'
    required: false
    default: 'false'
outputs:
  shell_versions:
    description: 'List of shell versions'
runs:
  using: 'node20'
  main: '../dist/collect-shell-versions/index.js'
