name: 'Collect shell versions'
description: 'Collect shell versions'
inputs:
  include-latest:
    description: 'Include "latest" tag in the list of shell versions'
    required: false
    default: 'false'
  exact-tags:
    description: 'List of comma separated exact dist tags to create list of versions from'
    required: false
    default: ''
  versions-length:
    description: 'Indicates how many versions should be in output'
    required: false
    type: number
    default: 3
  include-deprecated:
      description: 'Include deprecated dist tags in output'
      required: false
      default: 'false'
outputs:
  shell_versions:
    description: 'List of shell versions'
runs:
  using: 'node20'
  main: '../dist/collect-shell-versions/index.js'
