name: Create tenant
description: 'Create tenant'
inputs:
  cy-domain-prefix:
    description: "Domain prefix"
    required: true
    type: string
  cy-user:
    description: "User"
    required: false
    default: "admin"
    type: string
  cy-password:
    description: "Password"
    required: true
    type: string
  cy-email:
    description: "Email"
    required: false
    type: string
    default: 'test@test.com'
  cy-management-user:
    description: "Management Tenant user"
    required: true
    type: string
  cy-management-password:
    description: "Management Tenant password"
    required: true
    type: string
  cy-management-url:
    description: "Management Tenant URL"
    required: true
    type: string
  apps-to-subscribe:
    description: 'List of comma separated apps to subscribe to tenant'
    required: false
    default: ''
outputs:
  tenant-id:
    description: "Tenant id"
runs:
  using: 'node20'
  main: '../dist/actions/create-tenant/index.js'
